server:
  port: 8081

spring:
  main:
    allow-circular-references: true

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: my_client
  credentials:
    secret: zKwFuLnVYdDOnBMqIbbBCuZiWNQaldsR
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    com.psc.sample.keycloak: DEBUG